id: 44f3b9ad06ef46f3a7b3c2a00d727457
initial_creation_type: ocr
source_metadata:
  volumes:
    11bca80135a043cea044599eb04e05e3:
      base_file: v041.txt
      image_group_id: I1PD95886
      title: དེ་ཁོ་ན་ཉིད་གྲུབ་པ་ཞེས་བྱ་བའི་རབ་ཏུ་བྱེད་པ།
      total_pages: 1349
      volume_number: 41
